package metrics

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	EventsProcessed = promauto.NewCounter(prometheus.CounterOpts{
		Name: "ai_guardd_events_processed_total",
		Help: "Total number of events processed",
	})

	AlertsGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "ai_guardd_alerts_generated_total",
		Help: "Total number of alerts generated by risk level",
	}, []string{"risk"})

	IPsBanned = promauto.NewCounter(prometheus.CounterOpts{
		Name: "ai_guardd_ips_banned_total",
		Help: "Total number of IP addresses banned",
	})

	ConfigReloads = promauto.NewCounter(prometheus.CounterOpts{
		Name: "ai_guardd_config_reloads_total",
		Help: "Total number of configuration reloads",
	})

	TrackedEntities = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "ai_guardd_tracked_entities",
		Help: "Current number of tracked entities (IPs)",
	})
)

// StartServer starts the Prometheus metrics HTTP server
func StartServer(addr string) error {
	http.Handle("/metrics", promhttp.Handler())
	return http.ListenAndServe(addr, nil)
}
